# Exercicio sobre Variaveis.
a = input("Digite algo:")
print("O tipo primitivo desse valor é", type(a))
print("Só tem espaços?", a.isspace())
print("É um numero?" , a.isnumeric())
print("É alfabetico?" , a.isalpha())
print("É alfanumerico?" , a.isalnum())
print("Esta em maiscula?" , a.isupper())
print("Esta em minuscula?" , a.islower())
print("Esta capitalizado?" , a.istitle())